import type { SigningIntent } from './types.js'
import crypto from 'node:crypto'

/** Builder for creating signing intents with a fluent API */
export class IntentBuilder {
  private action: 'a2a.message.sign' | 'a2a.credential.issue' | 'did.update' = 'a2a.message.sign'
  private payload: SigningIntent['payload'] = { content: '' }
  private agentId: string
  private nonce: string = crypto.randomUUID()

  constructor(agentId: string) {
    if (!agentId || agentId.trim().length === 0) {
      throw new Error('agentId is required')
    }
    this.agentId = agentId
  }

  /** Set the action type (default: a2a.message.sign) */
  setAction(action: 'a2a.message.sign' | 'a2a.credential.issue' | 'did.update'): this {
    this.action = action
    return this
  }

  /** Set the payload content */
  setPayload(
    content: string,
    contentType?: string,
    recipientDID?: string
  ): this {
    this.payload = {
      content,
      content_type: contentType,
      recipient_did: recipientDID,
    }
    return this
  }

  /** Override the nonce (auto-generated by default) */
  setNonce(nonce: string): this {
    if (!nonce || nonce.length < 16) {
      throw new Error('nonce must be at least 16 characters')
    }
    this.nonce = nonce
    return this
  }

  /** Build the signing intent (auto-sets timestamp) */
  build(): SigningIntent {
    return {
      action: this.action,
      payload: { ...this.payload },
      agent_id: this.agentId,
      timestamp: Math.floor(Date.now() / 1000),
      nonce: this.nonce,
    }
  }
}

/** Create a new IntentBuilder */
export function createIntent(agentId: string): IntentBuilder {
  return new IntentBuilder(agentId)
}
